---
- name: install,start and enable webserver
  hosts: all
  become: true
  tasks:
  - name: Install apache 
    apt:
      name: apache2
      state: present
  - name: Start service httpd, if not started
    service:
     name: apache2
     state: started
  - name: Enable service httpd, and not touch the state
    service:
      name: apache2
      enabled: yes
